### ISSUE TITLE
Slowness identified during load for the requests during the first 1-2 sec immediately server restart

### ISSUE THREAD

**Issue by garimella99** [r2dbc/r2dbc-pool#81] opened 2020-08-03 05:22 UTC
Slowness identified during load for the request in the first 1 sec immediately server restart.
Subsequent requests as well as re-run without restart has a stable and 90% better performance response compared to the first one sec.
Server Env details: spring boot webflux with r2dbc pool deployed in ECS fargate and connecting to Postgres Aurora cluster. pool settings - maxSize,initialSize is 200 Using spring data r2dbc
spring boot - 2.3.0.RC1
reactor-netty - 0.9.7. RELEASE
r2dbc-pool - 0.8.2.RELEASE
load is triggered after making sure pool is initialized.
Client : A gatling script with a very minimal load of 1000 users with a ramp time of 50 sec is configured in AWS EC2 in same VPC.

client Scenario
1) ECS server started.
2) wait for 4 min.
3) did a dry run of 5 requests using postman and 1 request using gatling client
3) trigger load using gatling

There is no slow query log registered in the Postgres DB.
Attached the log file. Not to sure how to fine-tune it.
This behaviour is consistently observed during the first 1-5 seconds only of the total load of 50 sec.
Any help is appreciated.

Thanks.
[logs-insights-r2dbc-1000users.xlsx](https://github.com/r2dbc/r2dbc-pool/files/5014012/logs-insights-r2dbc-1000users.xlsx)

**Comment by mp911de** [comment] 2020-08-03 07:28
The connection pool uses FIFO semantics which means that all 200 connections get connected first, before your application has properly warmed up. Connection creation is expensive, therefore you should warm up the pool. `ConnectionPool` exposes a `warmup()` method. You should be able to register a `BeanPostProcessor` to initiate warmup at application startup when using Spring Boot.

Please also note that the mentioned dependency versions are outdated as Spring Boot 2.3.2.RELEASE and `r2dbc-pool` 0.8.4.RELEASE are available since a while.

Please let us know whether you were able to observe a change in performance behavior.

**Comment by garimella99** [comment] 2020-08-03 15:19
thanks for your reply..

I  did 5 requests after 4 min of startup so make sure the applications is warmed up. And also made sure the 200 channels are connected on port 5432 before sending load.

 [actor-tcp-nio-2] r.netty.resources.NewConnectionProvider  : [id: 0x4cac70cd, L:/<removed> - R:<removed>:5432] Connected new channel
[actor-tcp-nio-2] r.netty.resources.NewConnectionProvider  : [id: 0x4cac70cd,L:/<removed> - R:<removed>:5432] onStateChange([connected], SimpleConnection{channel=[id: 0x4cac70cd, L:/<removed> - R:<removed>:5432]]})

Is the above activity is not considered warm up?

Want to  understand what this warm will actually do. Can help to explain.  According to below url it does not give much info.
https://javadoc.io/static/io.r2dbc/r2dbc-pool/0.8.3.RELEASE/io/r2dbc/pool/ConnectionPool.html#warmup--

Meanwhile as suggested  I will update to the latest version of spring boot and r2dbc-pool and apply warmup and observe the behaviour.

Thanks.

**Comment by mp911de** [comment] 2020-08-03 16:03
Warmup creates `initialSize` connections. If you have 10 initial connections and a cap at 200, then warmup will initialize 10 connections only. You might want to increase `initialSize` or perform a custom warming to ensure all 200 connections are active at startup.

Each time you see `connected new channel`, the driver creates a new connection.

**Comment by garimella99** [comment] 2020-08-04 02:18
I have initialSize and maxSize defined as 200. For all 200 connections I had observed the channel log with the message  "Connected new channel"  before triggering load.
So I assume the warmup is done before sending load. 
Thanks.

**Comment by garimella99** [comment] 2020-08-11 11:16
I tried with Spring Boot 2.3.2.RELEASE and r2dbc-pool 0.8.3.RELEASE and observed the same behaviour.

**Comment by dkulig** [comment] 2020-08-28 09:33
@mp911de 
I am also experiencing slowness in my application. However, latency increase is only observed after an app (AWS Fargate task) is running for a couple of hours.

My setup: 
- MySQL running on AWS Aurora RDS (max available connections = 2000)
- 4 Fargate tasks
- ~20% mem usage is average, no spikes (Fargate task)
- 60% cpu usage spikes (Fargate task)
- two connections pools, one for write one for read (read-only pool is affected by latency increase)
- both pools have identical config:
```
initial-size: 30
max-size: 100
max-idle-time: 30m
max-acquire-time: 5s
max-create-connection-time: 5s
validation-query: SELECT 1
```

RDS metrics seem to be fine, no slow queries reported on the DB level.
I am using `r2dbc-proxy` to collect metrics. Very interesting fact is that the `validation query` is sometimes reported as the slow-query:
`message:  SlowQuery: Time:4069 Connection:140 Query:["SELECT 1"] `

Other related errors seen:
```
  message:  Scheduler worker in group main failed with an uncaught exception 
    stack_trace:  io.r2dbc.spi.R2dbcTimeoutException: Validation timed out after 5000ms
	at io.r2dbc.pool.ConnectionPool.lambda$null$7(ConnectionPool.java:126)
	at reactor.core.publisher.Mono.lambda$onErrorMap$29(Mono.java:3270)
	at reactor.core.publisher.Mono.lambda$onErrorResume$31(Mono.java:3360)
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:88)
	at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.onError(ScopePassingSpanSubscriber.java:97)
	at reactor.core.publisher.SerializedSubscriber.onError(SerializedSubscriber.java:124)
	at reactor.core.publisher.FluxTimeout$TimeoutMainSubscriber.handleTimeout(FluxTimeout.java:289)
	at reactor.core.publisher.FluxTimeout$TimeoutMainSubscriber.doTimeout(FluxTimeout.java:274)
	at reactor.core.publisher.FluxTimeout$TimeoutTimeoutSubscriber.onNext(FluxTimeout.java:396)
	at reactor.core.publisher.StrictSubscriber.onNext(StrictSubscriber.java:89)
	at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.onNext(ScopePassingSpanSubscriber.java:90)
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:73)
	at org.springframework.cloud.sleuth.instrument.reactor.ScopePassingSpanSubscriber.onNext(ScopePassingSpanSubscriber.java:90)
	at reactor.core.publisher.MonoDelay$MonoDelayRunnable.run(MonoDelay.java:117)
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:68)
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:28)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)
```

and:

```
  stack_trace:  org.springframework.dao.DataAccessResourceFailureException: Failed to obtain R2DBC Connection; nested exception is io.r2dbc.spi.R2dbcTimeoutException: Connection Acquisition timed out after 5000ms
	at org.springframework.data.r2dbc.connectionfactory.ConnectionFactoryUtils.lambda$getConnection$0(ConnectionFactoryUtils.java:70)
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
```

Any help will be much appreciated!

**Comment by mp911de** [comment] 2021-05-11 08:33
Closing this ticket as the issue is related to warmup and there's nothing left to do.

**Closed by mp911de** 2021-05-11 08:33 UTC
Labels: status: waiting-for-feedback
