### ISSUE TITLE
Connection unexpectedly closed exception

### ISSUE THREAD

**Issue by menakaprabu** [r2dbc/r2dbc-pool#152] opened 2022-01-24 21:45 UTC
I am using r2dbc-pool (0.8.8.RELEASE) where I am getting **Connection unexpectedly closed exception** for every 30 mins from boot time. It is not happening without using pool. I am using mssql protocol. Please suggest, what I am missing here.

**Comment by mp911de** [comment] 2022-01-25 08:57
Duplicate of #153

**Closed by mp911de** 2022-01-25 08:57 UTC
