### ISSUE TITLE
r2dbc pool only use one thread 

### ISSUE THREAD

**Issue by skyfour** [r2dbc/r2dbc-pool#191] opened 2023-06-14 10:30 UTC
## Feature Request
i use r2dbc hope not use one thread, otherwise one thread cpu is 100%

<img width="1678" alt="image" src="https://github.com/r2dbc/r2dbc-pool/assets/25677237/c31fe1ad-03fd-4ceb-877d-8239385b5e2a">

**Comment by mp911de** [comment] 2023-06-15 08:24
Duplicate of #190

**Closed by mp911de** 2023-06-15 08:24 UTC
